/* Generated by Together */

#ifndef CABUTTON_H
#define CABUTTON_H
#include "CaObject.h"
class CaGroup;
class CaButton : public CaObject {
public:

//	enum{FRAME_X_OFF=1,FRAME_Y_OFF=1};
public:
	/*!
		@brief 真正创建控件	
		@param iX 左上角横坐标
		@param iY 左上角纵坐标
		@param iW 宽度
		@param iH 高度
		@param pOwner 所属管理控件句柄
		@return <=-1 失败，>=0 成功
	*/
   virtual int Create(int iX,int iY,int iW,int iH);
   virtual int SetFocusIn();
   virtual int SetFocus();
   virtual	int ReFresh();

   virtual int ProcEvent(int iEvent,unsigned char *pEventData, int iDataLen);
//   CaButton(bool bFrame);
   CaButton(CaGroup *pOwner=NULL);
    virtual ~CaButton();
};
#endif //CABUTTON_H


