/* Generated by Together */

#ifndef CABUTTONLIST_H
#define CABUTTONLIST_H

#include "CaObject.h"
#include "CaButton.h"
#include "CaGroup.h"
#include "CaScrollGroup.h"

class CaButtonList : public CaScrollGroup {

public:

	CaButton * CreateNewButton(void);
    virtual void Add(CaObject *pObj);
	CaButtonList(int colCount);
	CaButtonList();
	~CaButtonList();

};
#endif //CABUTTONLIST_H


