/* Generated by Together */

#ifndef CAINPUTLIST_H
#define CAINPUTLIST_H
#include "CaObject.h"
#include "CaButton.h"
#include "CaInput.h"
#include "CaGroup.h"
#include "CaScrollGroup.h"
class CaInputList : public CaScrollGroup {
public:

private:
	int m_iInputCount; 

public:	
	CaInput * CreateNewInput(void);
	CaButton * CreateNewButton(void);
    virtual void Add(CaObject *pObj);
	CaInputList(int colCount, int InnerObjNum=0);
	CaInputList();
	~CaInputList();

	int GetBtnCount(){return m_iInputCount;}
};
#endif //CaInputList_H


