 /* Generated by Together */

#ifndef CALABLE_SELECT_H
#define CALABLE_SELECT_H
#include "CaObject.h"

class CaLabelSelect : public CaObject {
private:
    int m_iTitleLen;
	ALIGN_TYPE m_iAlignType;
    unsigned char m_caTitle[OBJ_TITLE_MAX_LEN+1];
	unsigned char m_caTitleImgBuf[OBJ_TITLE_MAX_LEN*IMG_BYTES];
    char m_antiString[OBJ_TITLE_MAX_LEN+1];
	unsigned char m_antiDispBuf[OBJ_TITLE_MAX_LEN*IMG_BYTES];
	
public:
	ALIGN_TYPE GetTitleAlign()const {return m_iAlignType;};
	void SetTitleAlign(ALIGN_TYPE alType);
	int SetFocus();
    virtual int SetFocusIn(void);
	virtual int SetTitle( const char * pData, int iLen);
	virtual int GetTitle( char *pData,int &iLen);
	virtual int ReFresh(void);
    virtual int ProcEvent(int iEvent, unsigned char * pEventData, int iDataLen);
	void SetAntiString(char *str);

	CaLabelSelect(bool bFocus,ALIGN_TYPE alType,int objtype=CA_LABEL);
	CaLabelSelect(bool bFocus,ALIGN_TYPE alType,CaGroup *pOwner);
	CaLabelSelect();
	virtual ~CaLabelSelect();
};
#endif //CALABLE_H


