 /* Generated by Together */

#ifndef CALABLE_H
#define CALABLE_H
#include "CaObject.h"

class CaLabel : public CaObject {
private:
    int m_iTitleLen;
	ALIGN_TYPE m_iAlignType;
    unsigned char m_caTitle[OBJ_TITLE_MAX_LEN+1];
	unsigned char m_caTitleImgBuf[OBJ_TITLE_MAX_LEN*IMG_BYTES];
public:
	ALIGN_TYPE GetTitleAlign()const {return m_iAlignType;};
	void SetTitleAlign(ALIGN_TYPE alType);
	int SetFocus();
    virtual int SetFocusIn(void);
	virtual int SetTitle( const char * pData, int iLen);
	virtual int GetTitle( char *pData,int &iLen);
	virtual int ReFresh(void);
	CaLabel(bool bFocus,ALIGN_TYPE alType,int objtype=CA_LABEL);
	CaLabel(bool bFocus,ALIGN_TYPE alType,CaGroup *pOwner);
	CaLabel();
	virtual ~CaLabel();
};
#endif //CALABLE_H


