/* Generated by Together */

#ifndef CALISTBOX_H
#define CALISTBOX_H
#include "CaGroup.h"
#include "CaScrollGroup.h"

class CaListBox : public CaScrollGroup {
private:
	//int m_iSelRowIndex; //del by flb
	ALIGN_TYPE m_iAlignType;
public:
	int  SelRowIndex()const{return m_iCurRowIndex;};
	void SelRowIndex(int rId){m_iCurRowIndex=rId;};

// 	int  SelRowIndex()const{return m_iSelRowIndex;};
// 	void SelRowIndex(int rId){m_iSelRowIndex=rId;}; //changed by flb
	
public:    

    CaListBox(ALIGN_TYPE altype=ALIGN_LEFT);
    virtual ~CaListBox();
	virtual int  Create(int iX,int iY,int iW,int iH);

	int AddNewLine(const char *pData,int iDataLen);
	int GetLineData(char *pData,int &iDataLen);
};
#endif //CALISTBOX_H


