/* Generated by Together */

#include "CaListBox.h"
#include "CaLabel.h"

#include"LOGCTRL.h"
#include "pos_debug.h"

CaListBox::CaListBox(CaObject::ALIGN_TYPE altype)
{
	//m_iSelRowIndex=0;
	m_iColCount=1;
	m_iAlignType=altype;
}
CaListBox::~CaListBox()
{

}
int  CaListBox::Create(int iX,int iY,int iW,int iH)
{
	CaScrollGroup::Create(iX,iY,iW,iH);
	RowH(WORD_H);
	return 1;
}

int CaListBox::AddNewLine(const char *pData,int iDataLen)
{
	CaLabel *lb=new CaLabel(true,m_iAlignType,this);
	lb->Create(0,0,ColW(),RowH());
	lb->SetTitle(pData,iDataLen);
	
//		CaLabel(bool bFocus,ALIGN_TYPE alType,int objtype=CA_LABEL);
	return 1;
}
int CaListBox::GetLineData(char *pData,int &iDataLen)
{
	return 1;
}



