 /* Generated by Together */

#include "CaScrollBar.h"

#include"LOGCTRL.h"
#include"pos_debug.h"

CaScrollBar::CaScrollBar()
{
	 m_iTotalLines=1;
	 m_iDispLines=1;
	 m_iCurIndex=0;
	 m_iBoxType=BOX_ALL;
	 m_iPreIndex=-1;	
}

CaScrollBar::~CaScrollBar()
{
}

int CaScrollBar::GetBarPosition(void)
{
	DBG_ASSERT_EXIT(m_iTotalLines > 1,("m_iTotalLines=%d is invalid!") );
	if( m_iCurIndex == 0)
	{
		return 0;
	}
	else
	{
		double p=0.00;
		double h=0.00;

		h=((double)((m_iTotalLines-m_iDispLines)*m_iH))/(double)(m_iTotalLines-1);
		p=(h*(double)m_iCurIndex)/((double)(m_iTotalLines-1))+1;
		return (int)p;
	}
}
int CaScrollBar::GetBarLength(void)
{
	DBG_ASSERT_EXIT(m_iTotalLines > 1,("m_iTotalLines=%d is invalid!") );
	double h=0.00;
	h=((double)((m_iDispLines-1)*m_iH))/(double)(m_iTotalLines-1);
	return (int)h;
}

void CaScrollBar::DrawBox()
{
	LCDFillRect(m_iX,m_iY,m_iW,m_iH,0);
	CaObject::DrawBox();
//	DBG_PRN("info",("p=%d,l=%d",GetBarPosition(),GetBarLength()));
	if(m_iCurIndex == m_iTotalLines-1)
	{
		int p=(m_iH-GetBarLength());
		LCDFillRect(m_iX, m_iY+p, m_iW, GetBarLength() ,1);
	}
	else
	{
		LCDFillRect(m_iX, m_iY+GetBarPosition(), m_iW, GetBarLength() ,1);
	}
}
int CaScrollBar::ReFresh()
{
//	if(m_iCurIndex == m_iPreIndex  ) 
	if(m_iTotalLines > 1 && m_iTotalLines >m_iDispLines)
		DrawBox();
	return 1;
}
int CaScrollBar::Create(int iX,int iY,int iW,int iH)
{
	return	CaObject::Create(iX,iY,iW,iH);
}
void CaScrollBar::CurIndex(int i)
{
	DBG_ASSERT_WARNING(i < m_iTotalLines,("i=%d > m_iTotalLines=%d !",i,m_iTotalLines));
	m_iCurIndex=i;
};


