  /* Generated by Together */

#ifndef CASCROLLGROUP_H
#define CASCROLLGROUP_H
#include "CaGroup.h"
#include "CaScrollBar.h"

class CaScrollGroup : public CaGroup {
public:
	typedef enum _ScrollBarPos_{LEFT_SCROLL_BAR=0,RIGTH_SCROLL_BAR,NO_SCROLL_BAR}TScrollBarPos; 
	enum {DEFAULT_ROW_H=CHAR_H+1,
		DEFAULT_COL_W=10*CHAR_W,
		DEFAULT_ROW_INTERVAL=1, 
		DEFAULT_COL_INTERVAL=8,
		DEFAULT_BAR_W=2};
protected:
	/*! 显示行高 */
	int m_iRowH;
	/*! 显示列宽 */
	int m_iColW;
public:

	/*! 行数*/
	int m_iRowCount;
	/*! 显示最大行数*/
	int m_iDispRowCount; 
	/*! 当前行号*/	
	int m_iCurRowIndex;
	/*! 屏幕上的当前行号*/
	int m_iCurScrRowIndex;
	/*! 列数 */
	int m_iColCount;
	/*! 当前列序号*/
	int m_iCurColIndex;
	CaScrollBar *m_pScrollBar;
	/*! 滚动条的位置*/
	int m_iScrollBarPos;
	/*! 滚动条宽度 */
	int m_iScrollBarW;
	/*! 行间距 */
	int m_iRowInterval;
	/*! 列间距 */
    int m_iColInterval;
	
	/*! 记录特殊按钮情况 */
    int m_iInnerObjNum;
	
public:

	int  RowH()const{return m_iRowH;}
	void RowH(int h);
	int  ColW()const{return m_iColW;	}
	void ColW(int w){m_iColW=w;}
	int  RowCount()const{return m_iRowCount;};
	void RowCount(int c){m_iRowCount=c;}
	int  ColCount()const{return m_iColCount;}
	void ColCount(int c){m_iColCount=c;	}
	void DispRowCount(int c);
	int  DispRowCount()const{return m_iDispRowCount;};
	int	 CurRowIndex()const{return m_iCurRowIndex;};
	void CurRowIndex(int i){m_iCurRowIndex=i;}
	void ScrollBarW(int w){m_iScrollBarW=w;	}
	int  ScrollBarW()const{return m_iScrollBarW;}
	void RowInterval(int i  ){m_iRowInterval=i;}
	int  RowInterval()const {return m_iRowInterval;}

	void ReSetFocus();
//	void ColInterval(int i){m_iColInterval=i;}
//	int  ColInterval()const{return m_iColInterval;}
public:    
	//CaScrollGroup(int type=CA_SCROLL_GROUP);
	CaScrollGroup(int type=CA_SCROLL_GROUP, int InnerObjNum=0);
	virtual ~CaScrollGroup();
	virtual int  Create(int iX,int iY,int iW,int iH);
    virtual int  ProcEvent(int iEvent,unsigned char *pEventData, int iDataLen);
	virtual int  ReFresh(void);
	virtual int  SetFocus(void);	
 	virtual void End(void);
	virtual void SetFocusToObj(const CaObject *targetObj, int BtnNumOfCol = 4);
protected:

	virtual int OnLeftKey();
	virtual int OnRightKey();
	virtual int OnUpKey();
	virtual int OnDownKey();
	virtual void DrawScrollBar();
	virtual void DrawDispRows();
	 /*! 调整滚动条在对象列表中的位置，始终让它处在列表的末尾*/
	 void AdaptScrollbarOrder();

	 /*! 根据显示行数来计算行高*/
	 int CalculateRowH();

//	/*! 根据显示行数和行高来计算行间距 */
//	 int  CalculateRowInterval();

	 /*! 根据行高来算显示行数 */
	 int  CalculateDispRowCount();
	 /*! 重建可获得焦点对象的列表*/
	 void ReCreateFocusList();

	
};
#endif //CASCROLLGROUP_H



